### ISSUE TITLE
Not possible to set arrays

### ISSUE THREAD

**Issue by potmo** [richardszalay/fastlane-plugin-act#5]
I'm trying to set an array in a plist like so
```
    act(
        ipa: ipaPath,
        plist_file: "Info.plist",
        app_name: "Some.app",
        plist_values: {
            ":CFBundleLocalizations" => ["en", "fr", "de"]
        }
    )
```
and that does not work. I think the array needs to be mapped somehow before it's passeed to plistbuddy

**Comment by richardszalay** [comment]
That's true, setting arrays isn't supported. But you can get around it by specifying commands:

    act(
        ipa: ipaPath,
        plist_file: "Info.plist",
        app_name: "Some.app",
        plist_commands: {
            "Delete :CFBundleLocalizations", # If it's there by default
            "Add :CFBundleLocalizations array",
            "Add :CFBundleLocalizations:0 string 'en'",
            "Add :CFBundleLocalizations:1 string 'fr'",
            "Add :CFBundleLocalizations:2 string 'de'",
        }
    )

Failing that, I'll happily accept a PR as long as it contains unit tests :)
