### ISSUE TITLE
Support patching launch image

### ISSUE THREAD

**Issue by skrach** [richardszalay/fastlane-plugin-act#9]
First thank you for your plugin!

We are using different launch images in our app, therefore it would be a good addition if the plugin could also support patching different launch images.

**Comment by richardszalay** [comment]
Hi there, glad you're finding the plugin useful!

Launch images are tricky as they get compiled into the Assets.cat file, and I haven't looked into the complexity of patching those.

As an alternative, if you don't mind simply shipping all of the various launch images with your app when it compiles, you can use `act` to patch `:UILaunchStoryboardName` in your Info.plist

**Comment by skrach** [comment]
Hello and thank you for your response!

I think there is at least another way to provide launch images. In our app we're providing the `UILaunchImages` entry in the `Info.plist` file. This entries reference png files within the app bundle. What I'm currently doing, is replacing the files in the bundle using a shell script.

I agree that all other assets get compiled into a binary file (assets.car i think). I also don't know how this file could be patched.

**Comment by richardszalay** [comment]
Interesting. So you're saying that UILaunchImages reference files outside the asset catalog?

**Comment by skrach** [comment]
Yes exactly.

To be clear. The project is defined as following: In the _General_ tab of the project a Launch Image Source is provided. This value references an entry in the asset catalog of this project.

When generating the ipa file. Xcode moves the images provided in this asset catalog to the root of the ipa file and creates references to those files in the `Info.plist` file.

**Comment by richardszalay** [comment]
Your current method is probably the way to do. You could have a look at using act's internal API ([`IPAArchive`](https://github.com/richardszalay/fastlane-plugin-act/blob/master/lib/fastlane/plugin/act/helper/ipa_archive.rb)), but is unlikely to change much but also isn't really documented/support:

```ruby
archive = ActHelper::IPAArchive.new "/your/path/to/your.ipa"
app_working_path = archive.local_path( archive.app_path("") ) # Temp path into the .app directory from the archive

FileUtils.mkdir_p app_working_path
# Copy YourLaunchImage.png into app_working_path

archive.replace( archive.app_path("YourLaunchImage.png") )
archive.clean # Remove the temp dir
```

(app_path returns the archive-relative path to the primary ".app/" folder. local_path returns the location of an archive-relative path in the temp working directory)

**Comment by richardszalay** [comment]
I might actually look at including some file patching support in act, similar to the way the plist options work.
